name: deploy-backend

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 构建 Spring Boot
      - name: Build backend
        run: |
          mvn clean package -DskipTests
        shell: bash

      # 4. 上传 jar 到服务器
      - name: Upload jar to server
        run: |
          scp -i ${{ secrets.SERVER_SSH_KEY }} partner-voting-server/target/*.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/app/app.jar
        shell: bash

      # 5. 重启容器
      - name: Restart backend container
        run: |
          ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd /opt/app && docker compose restart backend"
        shell: bash
